#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const LEXICON_PATH = path.join(ROOT, 'lib', 'lexicon-data.js');
const BEGIN = '<!-- STL:RULES:BEGIN -->';
const END = '<!-- STL:RULES:END -->';
const RULES_FILENAME = 'semantic-rules.md';
const PROJECT_INSTRUCTION_FILES = ['CLAUDE.md', 'AGENTS.md'];

const SEV_LABEL = {
  critical: 'critical',
  high: 'high',
  'medium-high': 'medium-high',
  medium: 'medium',
  low: 'low',
};

function detectHost() {
  if (process.env.PLUGIN_ROOT || process.env.PLUGIN_DATA || process.env.CODEX_PLUGIN_ROOT) return 'codex';
  if (process.env.CLAUDE_PLUGIN_ROOT || process.env.CLAUDE_PLUGIN_DATA) return 'claude';
  return 'auto';
}

function loadPairs() {
  delete require.cache[require.resolve(LEXICON_PATH)];
  const lex = require(LEXICON_PATH);
  return { zhPairs: lex.zhPairs, enPairs: lex.enPairs, order: lex.SEVERITY_ORDER };
}

function sortBySeverity(pairs, order) {
  return [...pairs].sort((a, b) => {
    const diff = (order[b.severity] || 0) - (order[a.severity] || 0);
    if (diff !== 0) return diff;
    return a.id.localeCompare(b.id, undefined, { numeric: true });
  });
}

function zhTableRows(zhPairs, order) {
  return sortBySeverity(zhPairs, order)
    .map((pair) => `| ${pair.id} | ${pair.wide} -> **${pair.narrow}** | ${SEV_LABEL[pair.severity] || pair.severity} | ${pair.scenario} |`)
    .join('\n');
}

function enTableRows(enPairs, order) {
  return sortBySeverity(enPairs, order)
    .map((pair) => `| ${pair.id} | ${pair.wide} -> **${pair.narrow}** | ${SEV_LABEL[pair.severity] || pair.severity} | ${pair.scenario} |`)
    .join('\n');
}

function generateRulesFile(zhPairs, enPairs, order) {
  const total = zhPairs.length + enPairs.length;
  return `# Semantic constraint rules (generated, do not edit manually)

> This file is generated by \`npm run build-rules\` from the semantic trap lexicon. Total trap pairs: ${total}.
> Regenerate it whenever the lexicon changes. Project instruction files keep only a short managed pointer that targets this file.

**Use case**: writing or editing instruction files such as skill / agent / command / prompt content.

**Core idea**: some words activate much wider semantic regions in an LLM than their everyday meaning suggests. Before writing, actively narrow them.

## Four checks for whether a term is a trap

1. Degree-based rather than binary
2. Forward-looking or possibility-heavy
3. Subjective judgment-heavy
4. Loose association space

## Known trap pairs (wide -> narrow)

Chinese:

| ID | Wide -> Narrow | Severity | Why it drifts |
|----|----------------|----------|---------------|
${zhTableRows(zhPairs, order)}

English:

| ID | Wide -> Narrow | Severity | Why it drifts |
|----|----------------|----------|---------------|
${enTableRows(enPairs, order)}

## When a wide term must stay

1. Add an explicit exclusion list
2. Force a structured output shape
3. Add counterexamples that look similar but are out of scope

## Self-check

- If you hit a wide term, replace it with the narrow term first
- If the wide term must stay, add boundary anchoring
- If a suspicious new term behaves like the four checks above, narrow it and consider adding it to the lexicon
`;
}

function generatePointerBlock(total) {
  const body = `## Semantic constraint rules

> This block is generated by \`npm run build-rules\`. Do not edit it manually.

Before writing or editing skill / agent / command / prompt instruction text, open \`${RULES_FILENAME}\` in the same directory (${total} trap pairs + four semantic checks) and narrow wide-boundary wording. If a wide term must stay, apply the boundary-anchoring guidance from that file.`;
  return `${BEGIN}\n${body}\n${END}`;
}

function extractManagedRegion(text) {
  const start = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end < start) return null;
  return text.slice(start, end + END.length);
}

function injectIntoFile(targetPath, block) {
  let existing = '';
  if (fs.existsSync(targetPath)) existing = fs.readFileSync(targetPath, 'utf8');

  const region = extractManagedRegion(existing);
  if (region !== null) return existing.replace(region, block);
  if (existing === '') return `${block}\n`;
  const sep = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${sep}${block}\n`;
}

function resolveTargets(argv) {
  const existingOnly = argv.includes('--existing');
  const hostIndex = argv.indexOf('--host');
  const rawHost = hostIndex >= 0 ? String(argv[hostIndex + 1] || '').toLowerCase() : '';
  const host = ['codex', 'claude', 'auto'].includes(rawHost) ? rawHost : detectHost();
  const positional = argv.filter((arg, idx) => {
    if (arg === '--check' || arg === '--existing' || arg === '--host') return false;
    if (hostIndex >= 0 && idx === hostIndex + 1) return false;
    return true;
  });

  if (existingOnly) {
    const baseDir = path.resolve(positional[0] || process.cwd());
    const targets = PROJECT_INSTRUCTION_FILES
      .map((name) => path.join(baseDir, name))
      .filter((targetPath) => fs.existsSync(targetPath));
    if (targets.length === 0) {
      console.error(`No CLAUDE.md or AGENTS.md found in ${rel(baseDir)}.`);
      process.exit(1);
    }
    return targets;
  }

  if (positional.length === 0) {
    const existingTargets = PROJECT_INSTRUCTION_FILES
      .map((name) => path.resolve(path.join(ROOT, name)))
      .filter((targetPath) => fs.existsSync(targetPath));
    if (existingTargets.length > 0) return existingTargets;
    const fallbackName = host === 'claude' ? 'CLAUDE.md' : 'AGENTS.md';
    return [path.resolve(path.join(ROOT, fallbackName))];
  }

  return positional.map((targetPath) => path.resolve(targetPath));
}

function rel(p) {
  return path.relative(ROOT, p) || p;
}

function main() {
  const argv = process.argv.slice(2);
  const check = argv.includes('--check');
  const targetMdPaths = resolveTargets(argv);

  const { zhPairs, enPairs, order } = loadPairs();
  const total = zhPairs.length + enPairs.length;
  const rulesContent = generateRulesFile(zhPairs, enPairs, order);
  const pointerBlock = generatePointerBlock(total);

  if (check) {
    for (const targetMdPath of targetMdPaths) {
      const rulesPath = path.join(path.dirname(targetMdPath), RULES_FILENAME);
      if (!fs.existsSync(rulesPath)) {
        console.error(`Rules file missing: ${rel(rulesPath)}. Run: npm run build-rules`);
        process.exit(1);
      }
      if (fs.readFileSync(rulesPath, 'utf8') !== rulesContent) {
        console.error(`${rel(rulesPath)} is out of sync with the lexicon. Run: npm run build-rules`);
        process.exit(1);
      }
      if (!fs.existsSync(targetMdPath)) {
        console.error(`Managed region missing: ${rel(targetMdPath)}. Run: npm run build-rules`);
        process.exit(1);
      }
      const region = extractManagedRegion(fs.readFileSync(targetMdPath, 'utf8'));
      if (region === null) {
        console.error(`Managed region missing in ${rel(targetMdPath)}. Run: npm run build-rules`);
        process.exit(1);
      }
      if (region !== pointerBlock) {
        console.error(`Managed region in ${rel(targetMdPath)} is out of sync. Run: npm run build-rules`);
        process.exit(1);
      }
      console.log(`OK: ${rel(rulesPath)} and ${rel(targetMdPath)} are in sync with the lexicon`);
    }
    process.exit(0);
  }

  for (const targetMdPath of targetMdPaths) {
    const rulesPath = path.join(path.dirname(targetMdPath), RULES_FILENAME);
    fs.writeFileSync(rulesPath, rulesContent, 'utf8');
    fs.writeFileSync(targetMdPath, injectIntoFile(targetMdPath, pointerBlock), 'utf8');
    console.log(`Wrote ${rel(rulesPath)} and managed pointer into ${rel(targetMdPath)}`);
  }
}

main();
